### ISSUE TITLE
Enhance RegisterSchemasTask to print/save the IDs of the published schemas

### ISSUE THREAD

**Issue by georgevad** [ImFlog/schema-registry-plugin#101]
When running the `registerSchemas` task no information about the IDs is printed/saved to a file for the published schemas and this is useful for configuring the event producer that uses the respective schemas.
We can get the id by querying the latest, but when publishing an older version of the schema the id no longer corresponds to the latest version.

**Comment by ImFlog** [comment]
Hello @georgevad,
Thank you for being interested in this plugin. This is indeed something that I didn't think about.
I think I will log the updated id as well as the creating an outputFile in the register task.

**Comment by ImFlog** [comment]
Hi again @georgevad,
I've just released 1.7.0 that contains the new feature. If you have any problem with it, please open a new issue :)
