### ISSUE TITLE
Querying multiple registries

### ISSUE THREAD

**Issue by toolkit** [ImFlog/schema-registry-plugin#105]
Hi there.

The maven plugin which this adapts supports specifying multiple schema registries.

https://docs.confluent.io/platform/current/schema-registry/develop/maven-plugin.html#schema-registry-test-compatibility

Is this also available with this plugin?

Thanks.

**Comment by ImFlog** [comment]
Hello @toolkit,
This is not possible at the moment but this is indeed a valid use case.
Let's keep this issue to follow the developments.
OFC if you want to give it a go I'll be glad to guide you, else I'll tackle this after my holidays 😉

**Comment by ImFlog** [comment]
Ok, after taking a look at the confluent maven plugin documentation (https://github.com/confluentinc/schema-registry/blob/master/maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojo.java), it seems to be pretty easy to add.
What bothers me is the download case, if the schema is available in two registry, only one file would be retrieved and in case of latest, that could mean different content. I am not sure that this is desirable ...

Can you elaborate a bit your use case @toolkit

**Comment by ImFlog** [comment]
Has I have no response from your side @toolkit I will close this issue. Do not hesitate to reopen it once you got some more time to explain in details what you would like the plugin to do.
