### ISSUE TITLE
Feature Request: Download and save schema metadata

### ISSUE THREAD

**Issue by ferozed** [ImFlog/schema-registry-plugin#122]
We have a use case, where we need to do custom serialization. As part of this, we need to make it compatible with the way confluent's schema-registry ecosystem works. i.e we need to encode the schema-id as the first four bytes of avro payload, followed by the payload itself.

Currently, when you download the schema, it does not get the metadata. It should not be too difficult to save schema-metadata, maybe in a different folder, as json files.

Currently, the schema-registry returns the following metadata when looking up schema by subject and version.

```
{
  "subject": "io.github.ferozed.MySubject",
  "version": 1,
  "id": 9580,
  "schema": "..."
}
```

So, the `DownloadTaskAction` could save this json with the same filename as `subjectName` in a different folder.

Any thoughts on this proposal?

**Comment by ImFlog** [comment]
Hello @ferozed, thank you for your interest in this plugin and sorry for the late answer.

I think we could modify the download task to add a flag that also retrieves the metadatas and saves them. I am not sure about the different folder part as that would need to be overloadable and would add another parameter to the download subjects definitions.
Adding another task is a possibility that would be the most flexible (we can add a new value for the ouput dir).

WDYT ?

**Comment by ferozed** [comment]
hi! Sorry for the late reply.

Yes, a separate task is also fine, although i do prefer one task. The advantage of this is that you can download schema and metadata in one GET request. Also.. you are guaranteed that the `schema-id` in the metadata matches the actual schema downloaded. This may not be the case if the schema changed between the calls to the two tasks.

**Comment by ImFlog** [comment]
Agreed on the consistency part.
I think we could try to adapt the download task with a global flag in the `DownloadSubjectExtension` (defaulting to `false`) that would also retrieve the metadata in a file suffixed by `-metadata` for instance.
I hope to have some time to work on this next week but if you are willing to attempt to contribute I can assist you 😉
