### ISSUE TITLE
Dependency avro-1.11.2 not found

### ISSUE THREAD

**Issue by rafaroca** [ImFlog/schema-registry-plugin#139]
Hi, after the update to `kafka-schema-registry-gradle-plugin:1.11.1`, my gradle build complains about a missing dependency. I read in the release notes that the plugin now uses a custom version of the avro plugin. That plugin however seems to lack publication. I could not find any hints in the release notes, that a different repository is used.

```
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.ImFlog.avro:avro:1.11.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/ImFlog/avro/avro/1.11.2/avro-1.11.2.pom
       - https://packages.confluent.io/maven/com/github/ImFlog/avro/avro/1.11.2/avro-1.11.2.pom
     Required by:
         project : > com.github.imflog.kafka-schema-registry-gradle-plugin:com.github.imflog.kafka-schema-registry-gradle-plugin.gradle.plugin:1.11.1 > com.github.imflog:kafka-schema-registry-gradle-plugin:1.11.1
```

**Comment by ImFlog** [comment]
Hi @rafaroca, the readme has been updated with the instructions to add jitpack as build repository.
I am not able to update the release notes for now (holiday) but it's a good idea, I will
