### ISSUE TITLE
JSON local reference

### ISSUE THREAD

**Issue by prabhpahul** [ImFlog/schema-registry-plugin#140]
Is the local reference for JSON, is it the standard given by the JSON schemas? Can we use a similar structure for Terraform or Mavin? I have been reading some stuff where using $id for $ref is not suggested.

Thank you again for your time and consideration

**Comment by ImFlog** [comment]
Hello @prabhpahul, the $ref is described in the JSON schema specs : https://json-schema.org/draft/2020-12/json-schema-core.html#section-8.2.3.1
Can you point me to the resources you mention about why it's not suggested to use $id and $ref ?

I don't get the part about Terraform and Maven and their link with the project though but feel free to elaborate on this matter :)

**Comment by prabhpahul** [comment]
Hi, thank you replying back. '#' fragments are used to point to schemas definition on the same document. Not sure how we are using '#' to point to separate schemas files? Is there additional piece of functionality added to the code to achieve it? Because when I deploy this to Schema Registry, the references are not resolved '#' in separate file paths without using the file name.

**Comment by ImFlog** [comment]
In this project, when you need to reference a local file for json schema, you can use `addLocalReference` on your subject to specify where to find the references.
When doing so, It will read the json schema and add it as a reference in the same file. It is required to put all the references in a single file for Confluent Schema registry (he knows about remote reference but not locals).
You can fin more information on this in the README : https://github.com/ImFlog/schema-registry-plugin#test-schemas-compatibility

**Comment by ImFlog** [comment]
Without news from you @prabhpahul I will close this issue. If you still encounter this, please comment again here and tag me and I will reopen the issue. 
Thanks
