### ISSUE TITLE
Support for IDL language(`.avdl`)

### ISSUE THREAD

**Issue by sgc109** [ImFlog/schema-registry-plugin#161]
Does it support not only `.avsc` file(JSON representation), but also `.avdl`(IDL representation) file at the moment?

**Comment by ImFlog** [comment]
Hello, 
The [confluent Kafka](https://github.com/confluentinc/schema-registry) registry only support avsc format. But I think you could generate avsc format from an avdl (and vice-versa). You can for instance use [this gradle plugin](https://github.com/davidmc24/gradle-avro-plugin#generating-schema-files-from-protocolidl) (being migrated to the apache avro project).
