### ISSUE TITLE
Does the "name" argument to "addReference" and "addLocalReference" do anything when using Avro schemas?

### ISSUE THREAD

**Issue by adaptivecchinitz** [ImFlog/schema-registry-plugin#171]
It appears that I can type whatever I want for the name, and the task still resolves the references and registers my schemas just fine. 

I took a quick look in the source code, and don't think I saw the name used in the [Avro schema parser](https://github.com/ImFlog/schema-registry-plugin/blob/master/src/main/kotlin/com/github/imflog/schema/registry/parser/AvroSchemaParser.kt), only in the [Json schema parser](https://github.com/ImFlog/schema-registry-plugin/blob/master/src/main/kotlin/com/github/imflog/schema/registry/parser/JsonSchemaParser.kt#L29).

Am I missing a spot that uses the name when working with Avro? If the name matters, I'd like to make sure I set it correctly.

Thanks!

---

And thanks, in general, for your work on this plugin! It's very useful!

**Comment by ImFlog** [comment]
Hello @adaptivecchinitz thank you for using this plugin and the kind words 🙇 

The Subject name is required for remote references by the Schema Registry client. IIRC it's the name that will be registered in the Schema Registry.
For the local reference in Avro you are probably right, it doesn't seem to be used with the custom Avro implementation. I am planning to try to improve the local schema parsing (see #162) and that may change. Also I don't want to add a breaking change on the Subject and I kinda like the consistency of the API even for distinct Schema type.
So It will probably stay like this for now.

Thank you for pointing that 🙏

**Comment by adaptivecchinitz** [comment]
Ok, I'll probably leave the name argument as an empty string, then, which works fine for me. Thanks for the quick reply!
