### ISSUE TITLE
Plugin doesn't support proxy settings

### ISSUE THREAD

**Issue by cgraving** [ImFlog/schema-registry-plugin#18]
I am trying to use the plugin to register schema, but seem to be having issues that the gradle plugin doesn't seem to honor or pass the proxy information to the client. I have tried every form of setting the proxy, command line args, env variables, gradle.properties, etc, but none are being used when the call is made through the CachedSchemaRegsitryClient from the maven plugin.

**Comment by cgraving** [comment]
I was able to finally able to resolve by putting the no proxy entry that mattered first in the list. Between gradle, and other systems it seems that some work with "," separation in the no proxy, some use "|" and putting the localhost first in the list worked for now.

**Comment by ImFlog** [comment]
Glad to hear that :)
