### ISSUE TITLE
Unable to reuse subjects

### ISSUE THREAD

**Issue by filpano** [ImFlog/schema-registry-plugin#183]
Hi. I am currently using version `2.1.1` of the plugin.
I have the following situation where I wish to reuse some Avro subjects:

```
import com.github.imflog.schema.registry.Subject
Subject mySubject = Subject("my-subject-value", "${schemasPath}/MySubject.avsc", "AVRO")
		.addLocalReference('ReferencedSubject', "${schemasPath}/ReferencedSubject.avsc")

schemaRegistry {
	url = '...'
	credentials {
		username = '...'
		password = '...'
	}
	config {
		subject('table-receipts-value', 'BACKWARD_TRANSITIVE')
	}
	quiet = false
	pretty = true
	register {
		subject(tableReceiptsSubject)
	}
	compatibility {
		subject(tableReceiptsSubject)
	}

}
```

when I try to run either `reigsterSchemasTask` or `testSchemasTask`, I get the following error:

```
Build file '/home/.../my-service/build.gradle' line: 43

A problem occurred evaluating root project 'my-service'.
> Could not find method Subject() for arguments [my-subject-value, /home/.../my-service/src/main/avro/MySubject.avsc, AVRO] on root project 'my-service' of type org.gradle.api.Project.
```

Looking at the decompiled code for the `Subject` class, it looks as follows:

```
public final data class Subject public constructor(inputSubject: kotlin.String, file: kotlin.String, type: kotlin.String) { 
...
}
```

which seems like it should match. I have the feeling that this is something rather trivial that I'm overlooking.

**Comment by ImFlog** [comment]
Hello,

It seems that you are using a build.gradle, in groovy.
Thus to instantiate a new class you have to use the `new` keyword.
You can take a look at the [example folder](examples/Avro/build.gradle) to see a working example with reusable subjects.

Hope it helps (if not tell me).
