### ISSUE TITLE
Test Schema Compatibility in JSON Format using kotlin objects

### ISSUE THREAD

**Issue by andrikoz** [ImFlog/schema-registry-plugin#184]
Hello , I guess this more of a feature request than an issue.

We are planning on adding a schema registry in our kafka stack.

At the moment we dont use any schema registry so,  in order to avoid any further implementation effort , the plan is to use KafkaJsonSchemaSerializer to extract and register new schema versions straight from kotlin objects which are always the single point of truth.

In order to proactively guard contract violations we d like to take advantage of confluent api and this plugin to test schema compatibility. I can check that there's a task that compares local files VS latest schema version but in order to do this we have to extract the schema definitions from objects to local files. Is there any plan to add such a functionality in this plugin ?

I can see the already existing `schema-registry:derive-schema` but it refers to message files and not objects. Thanks in advance!

**Comment by ImFlog** [comment]
Hello,

Thank you for being interested in this plugin.

IMHO, we should not add this kind of feature to the plugin as it would add too much responsibility to it. I want it to be as much as possible only a façade toward the schema registry (even if it is also able to parse local dependency).
One thing you could do is generate the schema definition file using another plugin and then pipe the output into this plugin.

WDYT ?

**Comment by andrikoz** [comment]
Hello @ImFlog , makes sense to keep the responsibility of the plugin scoped, thank you!
