### ISSUE TITLE
Java/Kotlin Version compatibility error on build

### ISSUE THREAD

**Issue by sandonjacobs** [ImFlog/schema-registry-plugin#185]
When running `./gradlew build` from master, I get the following error:

```
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileJava' (17) and 'compileKotlin' (1.8).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

Appears to stem from [this setting](https://github.com/ImFlog/schema-registry-plugin/blob/8c0c31a08b93ce381e467a97c1c6059213269ed5/build.gradle.kts#L35) in the `KotlinCompile` task.

**Comment by ImFlog** [comment]
Hello, this project targets Java 8 (for now).
Use a JDK 8 if you want to build this project locally.

To run the plugin in your Gradle project this should not matter though.

**Comment by sandonjacobs** [comment]
Thanks @ImFlog. Closing this issue.
