### ISSUE TITLE
Schema compatibility for non-existent subject

### ISSUE THREAD

**Issue by ashinohara** [ImFlog/schema-registry-plugin#22]
I would like to be able to have a CI pipeline for our avro schemas.  The steps would be:
- Check compatibility for all avro schemas
- Register all schemas

Compatibility check fails when a subject does not exist already in the schema registry.  The error code that gets returned is:

`> io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject not found.; error code: 40401`

Can we modify the behavior so that compatibility passes if there is no pre-existing schema for that subject?  I know that is not the way that the maven plugin currently behaves.

**Comment by ImFlog** [comment]
From my POV it seems fair to consider a new schema as compatible with the non existing version.
Problem is that I would have to catch the restclient exceptions and parse manually the content (as it's not a structured object) and this could be error prone in the future.
I will take a look at the client code to see if something cleaner is possible.

**Comment by ImFlog** [comment]
I added the requested feature in the version 0.6.0.
It is awaiting approval on the plugin portal. When available you should be able to use it as you wanted to.
Please do not hesitate to create a new issue if something goes wrong ;)

**Comment by ashinohara** [comment]
Fantastic, thank you!
