### ISSUE TITLE
Error trying to use plugin

### ISSUE THREAD

**Issue by brunodomenici** [ImFlog/schema-registry-plugin#29]
Hi,

I'm getting the erro when add this plugin:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.confluent:kafka-schema-registry:5.0.0.
     Searched in the following locations: https://plugins.gradle.org/m2/io/confluent/kafka-schema-registry/5.0.0/kafka-schema-registry-5.0.0.pom
     Required by:
         project : > com.github.imflog.kafka-schema-registry-gradle-plugin:com.github.imflog.kafka-schema-registry-gradle-plugin.gradle.plugin:0.7.0 > com.github.imflog:kafka-schema-registry-gradle-plugin:0.7.0

```
I've tried to add the dependency `implementation "io.confluent:kafka-schema-registry:5.0.0"`and worked fine.

Any ideas?

Thank you.

**Comment by ImFlog** [comment]
Hello, thank you for the interest in this plugin.
To be able to resolve `io.confluent` packages, you need to have the associated repository in your buildscripts. Something like:
```
buildscript {
   repositories {
       maven {
           url "http://packages.confluent.io/maven/"
       }
   }
```
If that doesn't help, could you please provide your build.gradle configuration ?

**Comment by brunodomenici** [comment]
That worked!
Thanks a lot and congrats for the project!
