### ISSUE TITLE
Plugin fails to pull "kafka-schema-registry-5.0.0"

### ISSUE THREAD

**Issue by dilipsundarraj1** [ImFlog/schema-registry-plugin#31]
Hi,

First of all thank you so much for your effort to support the schema-registry in gradle.

I am afraid that by adding the below config, I am getting an error message and I am not able to proceed forward.
```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.imflog:kafka-schema-registry-gradle-plugin:0.7.0"
    }
}
```

**Error Message:**
```
Could not find io.confluent:kafka-schema-registry:5.0.0.
Searched in the following locations:
  - https://plugins.gradle.org/m2/io/confluent/kafka-schema-registry/5.0.0/kafka-schema-registry-5.0.0.pom
  - https://plugins.gradle.org/m2/io/confluent/kafka-schema-registry/5.0.0/kafka-schema-registry-5.0.0.jar
  - https://plugins.gradle.org/m2/io/confluent/kafka-schema-registry/5.0.0/kafka-schema-registry-5.0.0.pom
  - https://plugins.gradle.org/m2/io/confluent/kafka-schema-registry/5.0.0/kafka-schema-registry-5.0.0.jar
```
Reason being the **kafka-schema-registry:5.0.0** is not available and I see only **5.2.1**.

You can check the same in the below link.
https://mvnrepository.com/artifact/io.confluent/kafka-schema-registry

Let me know if you need any information.

Thanks,
Dilip Sundarraj.

**Comment by ImFlog** [comment]
Hello, thank you for your interest in this plugin.
In order to fetch the confluent library, you need to add their repository in your buildscript like so:
```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "http://packages.confluent.io/maven/"
        }
  }
    dependencies {
        classpath "com.github.imflog:kafka-schema-registry-gradle-plugin:0.7.0"
    }
}
```

You are not the first one having trouble with this. I will keep this ticket the time for me to change the README to specify this explicitly.
