### ISSUE TITLE
SSL Capablities of the Schema Registry Plugin

### ISSUE THREAD

**Issue by mehmetsalgar** [ImFlog/schema-registry-plugin#49]
I am using Maven version of the Schema Registry and our Schema Registry is not with Basic Authentication protected but SSL Certificates. 

Normally we are delivering the SSL Certificate Parameters with -Djavax.ssl.trustStore and -Djavax.net.ssl.trustStorePassword but it seems they have no effect on the Gradle Plugin.

Then I debugged the SchemaRegistryClient from Confluent and I discoverd that it needs the parameters in the form of

io.confluent\kafka-schema-registry-client\6.0.0\\kafka-schema-registry-client-6.0.0.jar!\io\confluent\kafka\schemaregistry\client\CachedSchemaRegistryClient.class

Line 172:
`if (configs != null && !configs.isEmpty()) {
      restService.configure(configs);

      Map<String, Object> sslConfigs = configs.entrySet().stream()
          .filter(e -> e.getKey().startsWith(SchemaRegistryClientConfig.CLIENT_NAMESPACE))
          .collect(Collectors.toMap(
              e -> e.getKey().substring(SchemaRegistryClientConfig.CLIENT_NAMESPACE.length()),
              Map.Entry::getValue));
      SslFactory sslFactory = new SslFactory(sslConfigs);
      if (sslFactory != null && sslFactory.sslContext() != null) {
        restService.setSslSocketFactory(sslFactory.sslContext().getSocketFactory());
      }
    }`

So they have to start with SchemaRegistryClientConfig.CLIENT_NAMESPACE

`public static final String CLIENT_NAMESPACE = "schema.registry.";`

but converting parameters in graddle.properties didn't helped

schema.registry.javax.ssl.trustStore
schema.registry.javax.ssl.trustStorePassword

If seems these parameters must be over Config Maps from the SchemaRegistryClient delivered in the constructor.

io.confluent\kafka-schema-registry-client\6.0.0\\kafka-schema-registry-client-6.0.0.jar!\io\confluent\kafka\schemaregistry\client\CachedSchemaRegistryClient.class

Line 98:
`  public CachedSchemaRegistryClient(
      List<String> baseUrls,
      int identityMapCapacity,
      List<SchemaProvider> providers,
      Map<String, ?> originals) {
    this(new RestService(baseUrls), identityMapCapacity, providers, originals, null);
  }
`

The problem is Gradle Plugin ist only interested with the configuration parameter for Basic Authentication and does not deliver any other configuration.

https://github.com/ImFlog/schema-registry-plugin/blob/master/src/main/kotlin/com/github/imflog/schema/registry/download/DownloadTask.kt

`fun downloadSchemas() {
        val errorCount = DownloadTaskAction(
            RegistryClientWrapper.client(url.get(), basicAuth.get()),
            project.rootDir,
            subjects.get()
        ).run()
        if (errorCount > 0) {
            throw GradleScriptException("$errorCount schemas not downloaded, see logs for details", Throwable())
        }
    }`

I think plugin needs additional configuration parameters

from class
org.apache.kafka\kafka-clients\2.6.0\kafka-clients-2.6.0.jar!\org\apache\kafka\common\config\SslConfigs.class

ssl.truststore.location
ssl.truststore.password

and maybe keystores

ssl.keystore.location
ssl.keystore.password

**Comment by ImFlog** [comment]
Hello @mehmetsalgar thank you for the interest in the plugin.
I indeed think there is a missing piece.
This should be straightforward, add properties to the SchemaRegistryExtension and use them in the restClient.
The hardest part for me will be to start the schema registry with SSL enabled to test this ([this might help](https://github.com/Pierrotws/kafka-ssl-compose)).
I keep you posted.

**Comment by mehmetsalgar** [comment]
I manipulated the SchemaRegistry Client and Gradle Plugin Code during Debug Session, when the parameter

ssl.truststore.location
ssl.truststore.password
ssl.keystore.location
ssl.keystore.password

are in the Config Map, the SSL connection works....

A side note, when we are using this configuration

`download {
            subject('xxx-value', "${project.name}/build/schema/avro")
            subject('yyyy-value', "${project.name}/build/schema/avro")
        }`

Can you give us the option to use absolute paths for the output, momentan only option is relative...

So if I try to use following...

`download {
            subject('xxx-value', ""${project.buildDir.absolutePath}"")
            subject('yyyy-value', ""${project.buildDir.absolutePath}"")
        }`

while you are already concating the Absolute path before my configuration, it is not working, it is really troublesome with nested 
Gradle Projects..

Thx anyway, for quick respsonse....

**Comment by ImFlog** [comment]
I've just added the support for absolute path but I didn't had time to look the SSL part yet (see opened PR).
I think I will be able to get this done at the end of the week.

**Comment by mehmetsalgar** [comment]
Hi, any idea when you can publish SSL extension, I see that you made the changes. I plan to use the plugin in a Production project but I need the SSL capablities. If you can release it as SNAPSHOT or so, I can test the changes (I guess it will be difficult to build that test setup for you).

**Comment by ImFlog** [comment]
Hi,
I've just pushed the version 1.1.0-SNAPSHOT in the Gradle plugin portal. Please tell me if you find any issue.
I will try to start setting up tests tomorrow If I find the time. Then I will need to update the examples / add documentation.

**Comment by ImFlog** [comment]
I rolled back the move to version 11. Java 8 is once again the target. You should be able to try again.

**Comment by mehmetsalgar** [comment]
Is this the correct way to populate new ssl property

`ssl {
       ["ssl.truststore.location": "test"]
}`

when debug  CachedSchemaRegistryClient Line 170 config maps arrive empty....

**Comment by ImFlog** [comment]
The configuration looks like:
```
schemaRegistry {
                url = 'https://localhost:8181/'
                ssl {
                    configs = ["ssl.keystore.location": "/secret/path"]
                }
```
The config keys needs to come from : `org.apache.kafka.common.config.SslConfigs`

**Comment by mehmetsalgar** [comment]
Ok, thx for the tip...I got that part working, but as mentioned in the previous post, Schema Registry Client need as prefix..

public static final String CLIENT_NAMESPACE = "schema.registry.";

After you validate the entries against SslConfigs, you have add the keys in the map with this prefix, otherwise they are ignored by SslFactory...

**Comment by ImFlog** [comment]
Just pushed another version, I added the prefix and forced the map as <String, String>. Hope that will work. I have tried a bit to start the container in my tests with SSL but still not working (yet). So I am still blind regarding the development.

**Comment by mehmetsalgar** [comment]
Ok, I tested again and now everything works perfectly....

Thx for your help at the Weekend 👍 

When are you planing to do  a release version?

**Comment by ImFlog** [comment]
I think I am close. Hopefully I will release before the end of next week.

**Comment by ImFlog** [comment]
I've just added the examples and the integration test.
I will update the documentation tomorrow in the evening. If I find enough time I should be able to release afterward.

**Comment by mehmetsalgar** [comment]
Thx you very much for your help....
