### ISSUE TITLE
Switching schema registries with build flag

### ISSUE THREAD

**Issue by trevmex** [ImFlog/schema-registry-plugin#54]
Hello! I love this plugin, BTW! Thank you for making it!

One feature I am interested in is the ability to switch schema registries depending on which environment I am in (using something like a gradle project property).

(Please excuse my lack of gradle file formatting, this is just a pseudocode idea.)

What do you think?

```schemaRegistry {
    environment {
        name = 'prod'
        url = 'http://registry-url:8081/'
        download {
            // extension of the output file depends on the the schema type
            subject('avroSubject', '/absolutPath/src/main/avro')
            subject('protoSubject', 'src/main/proto')
            subject('jsonSubject', 'src/main/json')
        }
    }
    environment {
        name = 'staging'
        url = 'http://registry-url:8081/'
        download {
            // extension of the output file depends on the the schema type
            subject('avroSubject', '/absolutPath/src/main/avro')
            subject('protoSubject', 'src/main/proto')
            subject('jsonSubject', 'src/main/json')
        }
    }
}```

**Comment by ImFlog** [comment]
Hello, thank you for the kind words about the plugin :)
I think your use case can be handled using environment variables or gradle / systems properties (see https://docs.gradle.org/current/userguide/build_environment.html)
In the context of the schema registry that would look like this:
```groovy
schemaRegistry {
    url = registryUrl
    // Rest of the configuration
}
```
And then when you run your command you would do something like: `$ gradle -PregistryUrl='http://stageUrl:8081' downloadSchemasTask` in stage and `$ gradle -PregistryUrl='http://prodUrl:8081' downloadSchemasTask` in prod.

This allow you to customize easily the registry you want to target and include this in your CI.
Would it fulfill your use case ?

**Comment by ImFlog** [comment]
Since I've not received any response for a month, I'll close this. Do not hesitate to comment or open another issue if it's not working for you 😉
