### ISSUE TITLE
Failed to upgrade from 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by soumyajit-sahu** [ImFlog/schema-registry-plugin#58]
When I tried to upgrade from 0.8.0 to 0.9.0 and above, I get the following error-

An exception occurred applying plugin request [id: 'com.github.imflog.kafka-schema-registry-gradle-plugin', version: '1.2.0']
> Failed to apply plugin [id 'com.github.imflog.kafka-schema-registry-gradle-plugin']
   > Could not create an instance of type com.github.imflog.schema.registry.SchemaRegistryExtension_Decorated.
      > Could not find any public constructor for class com.github.imflog.schema.registry.SchemaRegistryExtension_Decorated which accepts parameters [].

Could we have some guidance on upgrade? I did notice that SchemaRegistryExtension was refactored in 0.9.0.

**Comment by ImFlog** [comment]
Hello @soumyajit-sahu,

The changes enforce that the extensions are all nested in the `schemaRegistry { }` block. Before that the plugin allowed you to define the various block anywhere in your build configuration (for instance `download {}` didn't had to be nested).
So If you followed the README, nothing has changed :)

If It still doesn't solve your issue, can you provide a redacted version of your build configuration so I can take a deeper look ?

**Comment by soumyajit-sahu** [comment]
Hello @ImFlog , thanks for looking into this issue.

Here is the redacted version of our build.gradle which works with version 0.7.0 and 0.8.0.
We use 
`com.commercehub.gradle.plugin:gradle-avro-plugin` too, but I have removed that reference from the below.

buildscript {
    ext {
        gradle_avro_plugin_version = '0.17.0'
    }
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "http://packages.confluent.io/maven/"
        }
        maven {
            url = uri("https://jitpack.io")
        }
    }
    dependencies {
        classpath "com.commercehub.gradle.plugin:gradle-avro-plugin:$gradle_avro_plugin_version"
//        classpath "com.github.imflog:kafka-schema-registry-gradle-plugin:0.9.0"
    }
}

plugins {
    id "com.github.imflog.kafka-schema-registry-gradle-plugin" version "0.9.0"
    id 'idea'
}


```gradle
schemaRegistry {
    url = "${schema_registry_endpoint}"
    compatibility {
        subject('subjectName', "pathToAvscFile")
    }
}
```

**Comment by ImFlog** [comment]
It may probably comes from the fact that the 2 plugins DLS are mixed in your configuration (See https://plugins.gradle.org/plugin/com.github.imflog.kafka-schema-registry-gradle-plugin/0.9.0). As you need to define the buildscript, you need to use the legacy DSL and thus use the apply plugin line.
This lead to something like this:
```
buildscript {
	ext {
		gradle_avro_plugin_version = '0.17.0'
	}
	repositories {
		jcenter()
		mavenCentral()
		maven {
			url "https://plugins.gradle.org/m2/"
		}
		maven {
			url "http://packages.confluent.io/maven/"
		}
		maven {
			url = uri("https://jitpack.io")
		}
	}
	dependencies {
		classpath "com.commercehub.gradle.plugin:gradle-avro-plugin:$gradle_avro_plugin_version"
        classpath "com.github.imflog:kafka-schema-registry-gradle-plugin:0.9.0"
	}
}
plugins {
	id 'idea'
}

apply plugin: "com.github.imflog.kafka-schema-registry-gradle-plugin"

schemaRegistry {
	url = "https://localhost:9092"
	compatibility {
		subject('subjectName', "pathToAvscFile")
	}
}
```  
And it works well like this.
Does it solve your issue ?

**Comment by soumyajit-sahu** [comment]
Thanks @ImFlog for taking a look at this. That didn't help, but I did notice that we see this error only with gradle 4.10.2, but not with the latest (7.0) gradle version.
We have had other things failing with gradle 7.0, so it will take me time to debug through those.
I will close this issue as it is likely user error on our behalf.

Appreciate your support :)

**Comment by ImFlog** [comment]
Glad you understand better what's wrong.
The example directory works with gradle 5.6, It could be easier to migrate :)
Good luck
