### ISSUE TITLE
CompatibilityTaskAction - Option to only log errors

### ISSUE THREAD

**Issue by Slav4ik** [ImFlog/schema-registry-plugin#59]
We are running the compatibility test for a large repository of schemas.
The compatibility task creates many "non informative" log lines when schema is compatible.
I'd like to be able to decide if I want to see all logs or only logs for failure.

Specifically these 2 lines:
https://github.com/ImFlog/schema-registry-plugin/blob/ec01a72d000bd1f25d5ad4f08be5126123fd0631/src/main/kotlin/com/github/imflog/schema/registry/tasks/compatibility/CompatibilityTaskAction.kt#L49

**Comment by ImFlog** [comment]
Hello, thank you for using the plugin.

Could changing the log level globally be a fix for you ? https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level

Currently it's not possible to change the log level task by task (or even by package like we usually do in Java) see https://github.com/gradle/gradle/issues/1010

**Comment by Slav4ik** [comment]
Thank you for the great plugin, and for your quick response.

Globally I wouldnt like to turn off log levels as I do want visibility of the whole process.
Maybe a solution in the form of - exposing a configuration in the task, like "verbose" logging?

**Comment by ImFlog** [comment]
Given the previous link I think this approach makes sense.
I am currently in holiday so I cannot work on this, if you feel like creating the pull request it would be great, else I will do this in more than two weeks.

**Comment by ImFlog** [comment]
I am back !
After reading again your first message it seems that you want to remove the error logs too ?
If so, the `verbose` could be set to `true` by default (to keep current behavior) and set to `false` to disable all the logs messages.

Would it work for you ?

**Comment by ImFlog** [comment]
Available in 1.4.0.
