### ISSUE TITLE
specify file name for downloaded protos

### ISSUE THREAD

**Issue by nikoncode** [ImFlog/schema-registry-plugin#64]
It might be useful to specify a name for the downloaded protos as well as a path (already implemented).

**Comment by nikoncode** [comment]
This is actual use case for us, cause we use this plugin to download protos and then generate classes for java and python. And standard naming convention doesn't works.

**Comment by ImFlog** [comment]
I think this is a good idea.
This should be fairly simple for most of the case but It will not work for regexp download as we cannot put everything in the same file.
Do you want to submit a PR ? Else I can try to work on this during the weekend.

**Comment by ImFlog** [comment]
I've finally found time to work on this.
I will hopefully merge this and release a new minor version thursday.

If it works for your use case @nikoncode tell me ;)

**Comment by ImFlog** [comment]
It's available in 1.5.0
