### ISSUE TITLE
automatically download/upload references for protos

### ISSUE THREAD

**Issue by nikoncode** [ImFlog/schema-registry-plugin#65]
It might be useful for download to automatically fetch all available references (it might works for upload, but implementation will be much harder)

**Comment by ImFlog** [comment]
Hi @nikoncode, I am not completely how that would be possible.
How do you see this feature, should we download the subject and then parse it's content to understand that a reference is needed to then download it ? If yes, that seem a bit hard to do before #57 that will bring parsing library to the plugin (for JSON / Avro and Protobuf).

If you have any other implementation idea in mind I'd be glad to hear them :)

**Comment by ImFlog** [comment]
As i've not received any sign on this issue, I will close it (I already have a bunch awaiting).
If you have any other idea / a clearer use case do not hesitate to reopen it.
Thank you.
