### ISSUE TITLE
Mix Avro local and remote dependencies

### ISSUE THREAD

**Issue by ImFlog** [ImFlog/schema-registry-plugin#78]
For now we cannot mix local and remote dependencies.
If we use an ordered structure, we might be able to overcome the fact that some local dependencies may need a remote one and vice-versa.
That would requires some fetch using the registry before the global parsing (doable with the client).

**Comment by ImFlog** [comment]
This is probably not an ordering question in fact. If we treat the Avro file as a JSON, we could inline the local references and pass it to the schema registry as usual for remote dependencies resolution.

**Comment by mattdupuy** [comment]
Hello @ImFlog :)!
I was wondering if you had time to look into this issue.
We are using your plugin, many thanks for it by the way :smiley: , and we would love to be able to combine local and remote references.

**Comment by ImFlog** [comment]
Hello @mattdupuy, I was more working on adding the local references for protobuf recently (unsuccessfully at the moment).
But I can prioritize this as it's a user request now :)
Ofc if you want to give it a try I'll be glad to help

**Comment by mattdupuy** [comment]
Hello @ImFlog,
I will look at it this week. I am not a Gradle plugin expert, but I can give it a try.

**Comment by mattdupuy** [comment]
Hello again @ImFlog, I have push a PR on what we discuss, let me know what you think :)

**Comment by ImFlog** [comment]
Fixed by #112, thanks again :)
If anything doesn't work please reopen an issue.
